Repository GOSOPT-CDS-BAEMIN/server, pull requests merged in 2023-05, with the labels that each got.

#3 chore : 커밋 메시지 템플릿 추가
  .gitmessage.txt
Labels: 🐭 승희

#4 feat : 커스텀 응답형태 구현
  src/main/java/sopt/cds/baemin/common/dto/ApiResponse.java
Labels: 🔮 기능 구현, 🐭 승희

#6 feat: 엔티티 설계
  src/main/java/sopt/cds/baemin/controller/ExampleController.java
  src/main/java/sopt/cds/baemin/domain/Cart.java
  src/main/java/sopt/cds/baemin/domain/Food.java
  src/main/java/sopt/cds/baemin/domain/Review.java
  src/main/java/sopt/cds/baemin/domain/Store.java
  src/main/java/sopt/cds/baemin/domain/StoreImage.java
  src/main/java/sopt/cds/baemin/domain/StoreType.java
  src/main/java/sopt/cds/baemin/dto/ExampleDto.java
  src/main/java/sopt/cds/baemin/repository/ExampleRepository.java
  src/main/java/sopt/cds/baemin/service/ExampleService.java
Labels: 🗺️ 설계, 🐶 승준

#10 refactor: 응답 형태 커스터마이징 구체화
  src/main/java/sopt/cds/baemin/common/dto/ApiResponse.java
Labels: 🛠️ 리팩토링, 🗺️ 설계, 🐶 승준

#12 refactor : Success, Error 클래스에 isSuccess 필드 추가
  src/main/java/sopt/cds/baemin/common/dto/ApiResponse.java
  src/main/java/sopt/cds/baemin/exception/Error.java
  src/main/java/sopt/cds/baemin/exception/Success.java
Labels: 🛠️ 리팩토링, 🗺️ 설계, 🐶 승준

#11 feat : 매장 리뷰 조회 기능 구현
  src/main/java/sopt/cds/baemin/controller/ReviewController.java
  src/main/java/sopt/cds/baemin/domain/Review.java
  src/main/java/sopt/cds/baemin/dto/review/ReviewResponseDto.java
  src/main/java/sopt/cds/baemin/repository/ReviewRepository.java
  src/main/java/sopt/cds/baemin/repository/StoreRepository.java
  src/main/java/sopt/cds/baemin/service/ReviewService.java
Labels: 🔮 기능 구현, 🐶 승준

#22 fix: directory path 문제 해결
  src/resources/application.yml
Labels: ⚠️ 버그

#27 고객 엔티티 추가
  src/main/java/sopt/cds/baemin/domain/Cart.java
  src/main/java/sopt/cds/baemin/domain/Client.java
  src/main/java/sopt/cds/baemin/domain/Review.java
Labels: 🗺️ 설계

#26 refactor : 가게 타입별 조회, 가게 개별 조회, 가게 전체 조회 기능 리팩토링
  src/main/java/sopt/cds/baemin/controller/StoreController.java
  src/main/java/sopt/cds/baemin/domain/Store.java
  src/main/java/sopt/cds/baemin/dto/store/StoreInfoDto.java
  src/main/java/sopt/cds/baemin/exception/Error.java
  src/main/java/sopt/cds/baemin/repository/FoodRepository.java
  src/main/java/sopt/cds/baemin/repository/StoreCustomRepository.java
  src/main/java/sopt/cds/baemin/repository/StoreCustomRepositoryImpl.java
  src/main/java/sopt/cds/baemin/repository/StoreImageRepository.java
  src/main/java/sopt/cds/baemin/repository/StoreRepository.java
  src/main/java/sopt/cds/baemin/repository/StoreTypeRepository.java
  src/main/java/sopt/cds/baemin/service/StoreService.java
Labels: 🛠️ 리팩토링, 🐭 승희
